export const categories = [
  {
    id: 1,
    name: "Pizzas",
    image: require("../assets/images/hamburger.png"),
  },
  {
    id: 2,
    name: "Italiana",
    image: require("../assets/images/hamburger.png"),
  },
  {
    id: 3,
    name: "Mexicana",
    image: require("../assets/images/hamburger.png"),
  },
  {
    id: 4,
    name: "Japonesa",
    image: require("../assets/images/hamburger.png"),
  },
  {
    id: 5,
    name: "Sushi",
    image: require("../assets/images/hamburger.png"),
  },
];

export const features = {
  id: 1,
  title: "Feauture 1",
  description: "Descripción de la Categoría 1",
  restaurants: [
    {
      id: 1,
      name: "Restaurante 1",
      image: require("../assets/images/res.jpg"),
      description: "Descripción del Restaurante 1",
      lng: -99.1247860962787,
      lat: 19.297088979380817,
      address: "Calle Falsa 123",
      stars: 4.5,
      reviews: 120,
      category: "Mexicana",
      dishes: [
        {
          id: 1,
          name: "Taco",
          description: "Delicioso taco",
          price: 2.99,
          image: require("../assets/images/hamburger.png"),
        },
        {
          id: 2,
          name: "Quesadilla",
          description: "Rica quesadilla",
          price: 3.49,
          image: require("../assets/images/hamburger.png"),
        },
        {
          id: 3,
          name: "Enchilada",
          description: "Saborosa enchilada",
          price: 4.99,
          image: require("../assets/images/hamburger.png"),
        },
        {
          id: 4,
          name: "Tostada",
          description: "Crujiente tostada",
          price: 3.99,
          image: require("../assets/images/hamburger.png"),
        },
        {
          id: 5,
          name: "Guacamole",
          description: "Fresco guacamole",
          price: 5.99,
          image: require("../assets/images/hamburger.png"),
        },
      ],
    },
    {
      id: 2,
      name: "Restaurante 2",
      image: require("../assets/images/res2.jpg"),
      description: "Descripción del Restaurante 2",
      lng: -100.1332,
      lat: 18.4326,
      address: "Avenida Siempre Viva 742, Ciudad",
      stars: 4.0,
      reviews: 80,
      category: "Italiana",
      dishes: [
        {
          id: 1,
          name: "Pizza",
          description: "Pizza deliciosa",
          price: 8.99,
          image: "https://example.com/images/pizza.png",
        },
        {
          id: 2,
          name: "Pasta",
          description: "Pasta al dente",
          price: 7.99,
          image: "https://example.com/images/pasta.png",
        },
        {
          id: 3,
          name: "Lasaña",
          description: "Lasaña casera",
          price: 9.99,
          image: "https://example.com/images/lasagna.png",
        },
        {
          id: 4,
          name: "Ravioles",
          description: "Ravioles rellenos",
          price: 6.99,
          image: "https://example.com/images/ravioles.png",
        },
        {
          id: 5,
          name: "Tiramisú",
          description: "Postre tiramisú",
          price: 5.49,
          image: "https://example.com/images/tiramisu.png",
        },
      ],
    },
    {
      id: 3,
      name: "Restaurante 3",
      image: require("../assets/images/res.jpg"),
      description: "Descripción del Restaurante 3",
      lng: -98.1332,
      lat: 20.4326,
      address: "Calle Ejemplo 456, Ciudad",
      stars: 4.8,
      reviews: 150,
      category: "Japonesa",
      dishes: [
        {
          id: 1,
          name: "Sushi",
          description: "Sushi fresco",
          price: 12.99,
          image: "https://example.com/images/sushi.png",
        },
        {
          id: 2,
          name: "Ramen",
          description: "Ramen casero",
          price: 9.99,
          image: "https://example.com/images/ramen.png",
        },
        {
          id: 3,
          name: "Tempura",
          description: "Tempura crujiente",
          price: 11.99,
          image: "https://example.com/images/tempura.png",
        },
        {
          id: 4,
          name: "Gyoza",
          description: "Gyoza rellena",
          price: 7.99,
          image: "https://example.com/images/gyoza.png",
        },
        {
          id: 5,
          name: "Mochi",
          description: "Postre mochi",
          price: 4.49,
          image: "https://example.com/images/mochi.png",
        },
      ],
    },
    {
      id: 4,
      name: "Restaurante 4",
      image: require("../assets/images/res3.jpg"),
      description: "Descripción del Restaurante 4",
      lng: -97.1332,
      lat: 21.4326,
      address: "Avenida Ejemplar 789, Ciudad",
      stars: 4.3,
      reviews: 90,
      category: "Francesa",
      dishes: [
        {
          id: 1,
          name: "Croissant",
          description: "Croissant fresco",
          price: 3.99,
          image: "https://example.com/images/croissant.png",
        },
        {
          id: 2,
          name: "Quiche",
          description: "Quiche lorraine",
          price: 5.99,
          image: "https://example.com/images/quiche.png",
        },
        {
          id: 3,
          name: "Crepe",
          description: "Crepe dulce",
          price: 4.99,
          image: "https://example.com/images/crepe.png",
        },
        {
          id: 4,
          name: "Bouillabaisse",
          description: "Sopa de mariscos",
          price: 13.99,
          image: "https://example.com/images/bouillabaisse.png",
        },
        {
          id: 5,
          name: "Ratatouille",
          description: "Ratatouille tradicional",
          price: 8.49,
          image: "https://example.com/images/ratatouille.png",
        },
      ],
    },
    {
      id: 5,
      name: "Restaurante 5",
      image: require("../assets/images/res4.png"),
      description: "Descripción del Restaurante 5",
      lng: -96.1332,
      lat: 22.4326,
      address: "Calle Ejemplo Real 101, Ciudad",
      stars: 4.7,
      reviews: 200,
      category: "Española",
      dishes: [
        {
          id: 1,
          name: "Paella",
          description: "Paella valenciana",
          price: 14.99,
          image: "https://example.com/images/paella.png",
        },
        {
          id: 2,
          name: "Tapas",
          description: "Variedad de tapas",
          price: 9.99,
          image: "https://example.com/images/tapas.png",
        },
        {
          id: 3,
          name: "Gazpacho",
          description: "Sopa fría de tomate",
          price: 6.99,
          image: "https://example.com/images/gazpacho.png",
        },
        {
          id: 4,
          name: "Tortilla Española",
          description: "Tortilla de patatas",
          price: 7.49,
          image: "https://example.com/images/tortilla.png",
        },
        {
          id: 5,
          name: "Churros",
          description: "Churros con chocolate",
          price: 4.99,
          image: "https://example.com/images/churros.png",
        },
      ],
    },
  ],
};
